SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE TEST_USER;




/* Create Tables */

CREATE TABLE TEST_USER
(
	ID VARCHAR(64) NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	AGE INT NOT NULL,
	JOB VARCHAR(64) NOT NULL,
	-- 删除标记
	DEL_FLAG CHAR(1) DEFAULT '0' NOT NULL COMMENT '删除标记',
	-- 归属部门
	OFFICE_ID VARCHAR(64) COMMENT '归属部门',
	-- 创建者
	CREATE_BY VARCHAR(64) NOT NULL COMMENT '创建者',
	-- 创建时间
	CREATE_DATE DATETIME NOT NULL COMMENT '创建时间',
	-- 更新者
	UPDATE_BY VARCHAR(64) NOT NULL COMMENT '更新者',
	-- 更新时间
	UPDATE_DATE DATETIME NOT NULL COMMENT '更新时间',
	PRIMARY KEY (ID)
);



